
project_id = "hafxruwnggitvtyngedy"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[functions.collect-players-data]
verify_jwt = false

[functions.migrate-player-image]
verify_jwt = false

[functions.weekly-image-audit]
verify_jwt = false

[functions.rotate-daily-challenges]
verify_jwt = false
