// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hafxruwnggitvtyngedy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhZnhydXduZ2dpdHZ0eW5nZWR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzNDE0NTIsImV4cCI6MjA1NTkxNzQ1Mn0.gWlNlVeJyISEIjjfLN46hrZ7OZSKd_6rQFJ2LnUkVDw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
