import { useState } from 'react';

// Button artwork generated by Apple's documented image service. OAuth stays in
// the existing parent button, including native sign-in and funnel measurement.
export const AppleSignInArt = () => {
  const [failed, setFailed] = useState(false);
  return failed ? <span>Entrar com Apple</span> : (
    <img
      src="https://appleid.cdn-apple.com/appleid/button?height=48&width=180&color=white&border=false&type=sign-in&locale=pt_BR"
      alt="Entrar com Apple" width={180} height={48}
      className="h-12 w-[180px] max-w-full object-contain"
      onError={() => setFailed(true)}
    />
  );
};
